/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        orange: {
          50: '#fdf8f4',
          100: '#fbf0e8',
          200: '#f8dcd1',
          300: '#f6c5b4',
          400: '#f4b197',
          500: '#f29d66',
          600: '#e38450',
          700: '#c56839',
          800: '#9d4c26',
          900: '#7d3a1d',
          950: '#4a200e',
        },
        "tertiary-container": "#006e4b",
        "on-error": "#ffffff",
        "on-tertiary-container": "#67f4b7",
        "on-error-container": "#93000a",
        "secondary-fixed": "#c9e6ff",
        "secondary-container": "#39b8fd",
        "on-primary-container": "#dad7ff",
        "tertiary": "#005338",
        "tertiary-fixed-dim": "#4edea3",
        "surface-variant": "#d3e4fe",
        "surface-bright": "#f9f6f2",
        "error": "#ba1a1a",
        "inverse-primary": "#f8dcd1",
        "secondary-fixed-dim": "#89ceff",
        "on-secondary-fixed": "#001e2f",
        "primary-fixed-dim": "#f8dcd1",
        "on-tertiary-fixed-variant": "#005236",
        "on-primary": "#ffffff",
        "primary-container": "#e38450",
        "surface": "#f9f6f2",
        "surface-dim": "#cbdbf5",
        "tertiary-fixed": "#6ffbbe",
        "surface-tint": "#4d44e3",
        "on-secondary-fixed-variant": "#004c6e",
        "outline": "#777587",
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#f4b197",
        "background": "#f9f6f2",
        "on-primary-fixed-variant": "#c56839",
        "surface-container-highest": "#d3e4fe",
        "inverse-surface": "#213145",
        "primary": "#f29d66",
        "on-surface": "#0b1c30",
        "on-primary-fixed": "#7d3a1d",
        "secondary": "#006591",
        "on-background": "#0b1c30",
        "surface-container-low": "#eff4ff",
        "outline-variant": "#c7c4d8",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "surface-container": "#e5eeff",
        "on-surface-variant": "#464555",
        "on-secondary-container": "#004666",
        "on-tertiary-fixed": "#002113",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#dce9ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        lg: "40px",
        xl: "64px",
        base: "4px",
        md: "24px",
        sm: "16px",
        gutter: "24px",
        xs: "8px",
      },
      fontFamily: {
        "title-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
